name: modelport_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.21.0
  - pip>=21.0.0
  - pytorch>=1.13.0
  - onnx>=1.12.0
  - pip:
    - onnxruntime>=1.13.1
    - typer>=0.7.0
    - docker>=6.0.0
    - apache-tvm>=0.10.0  # TVM for native compilation
    - pillow>=9.2.0
    - tqdm>=4.64.0
    - pytest>=7.0.0
    - pytest-cov>=4.0.0 