name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.release.prerelease && 'testpypi' || 'pypi' }}
    permissions:
      id-token: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install apache-tvm
    
    - name: Build package
      run: python -m build
    
    - name: Publish package to TestPyPI
      if: github.event.release.prerelease
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
    
    - name: Publish package to PyPI
      if: ${{ !github.event.release.prerelease }}
      uses: pypa/gh-action-pypi-publish@release/v1 